import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import UpdateAvailableBuses from "./(components)/UpdateAvailableBuses";
import FindAvailableBusByDateAction from "@/Action/AvailableBusesByDate/FindAvailableBusByDateAction";
import FindAvailableRegisteredBusesAction from "@/Action/AvailableRegisteredBuses/FindAvailableRegisteredBusesAction";
import Nav from "./(components)/Nav";
import Image from "next/image";
import Logo from "../../public/images/booknowLogo.png";
import Menu from "./(components)/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const {buses}= await FindAvailableRegisteredBusesAction()

  // const { availableBuses } = await FindAvailableBusByDateAction();

  const res = await fetch("http://localhost:3000/api/availableBusByDate", {
    cache: "no-store",
  })
  const {availableBuses}=await res.json()
  console.log(availableBuses);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="space-y-10 relative overflow-hidden">
          <header className="flex flex-row justify-between px-5 items-center">
            <div className="flex flex-row space-x-5 items-center">
              <Link href="/">
                <Image src={Logo} alt="BookNow" className="w-[170px]"></Image>
              </Link>
              <div className="hidden md:block">
                <div className="flex flex-row space-x-5 items-center">
                  <Link href="/"> Home </Link>
                  <Link href="/BusRegisterPage"> Bus Register </Link>
                </div>
              </div>
            </div>
            <Menu></Menu>
            <UpdateAvailableBuses buses={availableBuses} />
          </header>

          {/* <Nav/> */}
          <div className="w-[90%] mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
